[project]
name = "exodo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "KIRAMA", email = "johan.quirama@upb.edu.co" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
exodo = "exodo:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
